version: "3.8"

services:
  # Background Scheduler - Runs trading logic
  scheduler:
    build: .
    container_name: trading-scheduler
    command: python trading_scheduler.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./results:/app/results
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/New_York # Market timezone
    restart: unless-stopped
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Streamlit Dashboard - Web interface
  dashboard:
    build: .
    container_name: trading-dashboard
    command: streamlit run streamlit_dashboard.py --server.headless=true --server.port=8501
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./results:/app/results
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/New_York
    restart: unless-stopped
    networks:
      - trading-network
    depends_on:
      - scheduler
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  trading-network:
    driver: bridge

volumes:
  trading-data:
  trading-logs:
  trading-results:
