name: truenorth-trading
region: nyc

services:
  # Backend API Service
  - name: true-north-platform
    github:
      repo: michwilf/true-north-platform
      branch: main
      deploy_on_push: true
    source_dir: /
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: professional-xs
    http_port: 8002
    health_check:
      http_path: /health
      port: 8002
      initial_delay_seconds: 60
    routes:
      - path: /
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALPHA_VANTAGE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/app"
      - key: CORS_ORIGINS
        value: "https://frontend-c9jafr23z-athleas-projects.vercel.app,https://frontend-athleas-projects.vercel.app,http://localhost:3002,http://127.0.0.1:3002"

