name: truenorth-trading
region: nyc

services:
  # Backend API Service
  - name: backend
    github:
      repo: YOUR_GITHUB_USERNAME/true-north-trading
      branch: main
      deploy_on_push: true
    source_dir: /
    dockerfile_path: /Dockerfile.backend
    instance_count: 1
    instance_size_slug: professional-xs
    http_port: 8002
    health_check:
      http_path: /health
      initial_delay_seconds: 60
    routes:
      - path: /
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALPHA_VANTAGE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/app"

  # Scheduled Worker Service
  - name: worker
    github:
      repo: YOUR_GITHUB_USERNAME/true-north-trading
      branch: main
      deploy_on_push: true
    source_dir: /
    dockerfile_path: /Dockerfile.worker
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALPHA_VANTAGE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/app"

